[2023-03-08 15:27:35,949][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:27:36,094][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:29:14,238][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:29:14,371][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:35:09,874][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:35:10,023][log_print.py 80][ERROR]: ------__init__执行失败：PySide6.QtCore.QObject.connect(): not enough arguments------
[2023-03-08 15:35:10,024][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 19, in __init__
    self.tab1()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 32, in tab1
    self.ui.pushButton1_1.connect(self.next(1))
TypeError: PySide6.QtCore.QObject.connect(): not enough arguments

[2023-03-08 15:37:10,724][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:37:10,864][log_print.py 80][ERROR]: ------__init__执行失败：PySide6.QtCore.QObject.connect(): not enough arguments------
[2023-03-08 15:37:10,864][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 19, in __init__
    self.tab1()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 32, in tab1
    self.ui.pushButton1_1.connect(self.next(1))
TypeError: PySide6.QtCore.QObject.connect(): not enough arguments

[2023-03-08 15:41:28,392][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:41:28,532][log_print.py 80][ERROR]: ------__init__执行失败：'PySide6.QtCore.QObject.connect' called with wrong argument types:
  PySide6.QtCore.QObject.connect(builtin_function_or_method, int)
Supported signatures:
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))------
[2023-03-08 15:41:28,532][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 19, in __init__
    self.tab1()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 32, in tab1
    self.ui.pushButton1_1.connect(next,1)
TypeError: 'PySide6.QtCore.QObject.connect' called with wrong argument types:
  PySide6.QtCore.QObject.connect(builtin_function_or_method, int)
Supported signatures:
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))

[2023-03-08 15:41:53,082][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:41:53,225][log_print.py 80][ERROR]: ------__init__执行失败：PySide6.QtCore.QObject.connect(): not enough arguments------
[2023-03-08 15:41:53,225][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 19, in __init__
    self.tab1()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 32, in tab1
    self.ui.pushButton1_1.connect(next)
TypeError: PySide6.QtCore.QObject.connect(): not enough arguments

[2023-03-08 15:42:06,000][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:42:06,126][log_print.py 80][ERROR]: ------__init__执行失败：'int' object is not an iterator------
[2023-03-08 15:42:06,126][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 19, in __init__
    self.tab1()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 32, in tab1
    self.ui.pushButton1_1.connect(next(1))
TypeError: 'int' object is not an iterator

[2023-03-08 15:45:24,925][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:45:25,064][log_print.py 80][ERROR]: ------__init__执行失败：'PySide6.QtCore.SignalInstance' object has no attribute 'connet'------
[2023-03-08 15:45:25,065][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 19, in __init__
    self.tab1()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 32, in tab1
    self.ui.pushButton1_1.clicked.connet(self.next(1))
AttributeError: 'PySide6.QtCore.SignalInstance' object has no attribute 'connet'

[2023-03-08 15:45:43,625][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:45:43,761][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:47:32,203][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:47:32,329][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:47:48,250][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:47:48,349][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:49:04,133][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:49:04,271][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:51:16,233][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:51:16,365][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:51:46,743][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:51:46,879][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 15:53:56,630][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:53:56,770][log_print.py 80][ERROR]: ------__init__执行失败：'PySide6.QtCore.SignalInstance' object has no attribute 'connnect'------
[2023-03-08 15:53:56,771][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 21, in __init__
    self.ui.pushButton1_1.clicked.connnect(self.next,1)
AttributeError: 'PySide6.QtCore.SignalInstance' object has no attribute 'connnect'

[2023-03-08 15:54:17,506][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 15:54:17,668][log_print.py 80][ERROR]: ------__init__执行失败：'PySide6.QtCore.QObject.connect' called with wrong argument types:
  PySide6.QtCore.QObject.connect(QPushButton, str, method, int)
Supported signatures:
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))------
[2023-03-08 15:54:17,668][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 21, in __init__
    self.ui.pushButton1_1.clicked.connect(self.next,1)
TypeError: 'PySide6.QtCore.QObject.connect' called with wrong argument types:
  PySide6.QtCore.QObject.connect(QPushButton, str, method, int)
Supported signatures:
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, Callable, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.QObject, PySide6.QtCore.QMetaMethod, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))
  PySide6.QtCore.QObject.connect(PySide6.QtCore.QObject, bytes, PySide6.QtCore.QObject, bytes, PySide6.QtCore.Qt.ConnectionType = Instance(Qt.AutoConnection))

[2023-03-08 16:05:23,408][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:05:23,557][log_print.py 80][ERROR]: ------__init__执行失败：SignalInstance() missing required argument 'slot' (pos 1)------
[2023-03-08 16:05:23,558][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 21, in __init__
    self.ui.pushButton1_1.clicked.connect(args=self.next2)
TypeError: SignalInstance() missing required argument 'slot' (pos 1)

[2023-03-08 16:06:04,976][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:06:05,111][log_print.py 80][ERROR]: ------__init__执行失败：SignalInstance() missing required argument 'slot' (pos 1)------
[2023-03-08 16:06:05,111][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 21, in __init__
    self.ui.pushButton1_1.clicked.connect(args=self.next2,item=1)
TypeError: SignalInstance() missing required argument 'slot' (pos 1)

[2023-03-08 16:07:01,523][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:07:01,666][log_print.py 80][ERROR]: ------__init__执行失败：SignalInstance() missing required argument 'slot' (pos 1)------
[2023-03-08 16:07:01,666][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 21, in __init__
    self.ui.pushButton1_1.clicked.connect(args=self.next2,kwargs=1)
TypeError: SignalInstance() missing required argument 'slot' (pos 1)

[2023-03-08 16:14:11,894][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:14:12,051][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:15:38,578][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:15:38,715][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:16:37,568][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:16:37,702][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:17:36,263][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:17:36,429][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:33:04,646][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:33:04,809][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:35:40,305][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:35:40,464][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:37:41,363][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:37:41,490][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:40:54,997][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:40:55,150][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 16:58:56,284][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 16:58:56,453][log_print.py 80][ERROR]: ------__init__执行失败：descriptor 'addTab' for 'PySide6.QtWidgets.QTabWidget' objects doesn't apply to a 'PySide6.QtWidgets.QWidget' object------
[2023-03-08 16:58:56,453][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 20, in __init__
    QTabWidget.addTab(self.ui.tab_1)
TypeError: descriptor 'addTab' for 'PySide6.QtWidgets.QTabWidget' objects doesn't apply to a 'PySide6.QtWidgets.QWidget' object

[2023-03-08 17:03:38,536][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:03:38,698][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:09:49,845][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:09:50,004][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:10:55,782][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:10:55,919][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:12:17,466][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:12:17,614][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:12:21,914][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 17:12:21,946][log_print.py 80][ERROR]: ------selectfile执行失败：'PySide6.QtWidgets.QFileDialog.getExistingDirectory' called with wrong argument types:
  PySide6.QtWidgets.QFileDialog.getExistingDirectory(Ui_Form, str)
Supported signatures:
  PySide6.QtWidgets.QFileDialog.getExistingDirectory(Optional[PySide6.QtWidgets.QWidget] = None, str = '', str = '', PySide6.QtWidgets.QFileDialog.Option = Instance(PySide6.QtWidgets.QFileDialog.Option.ShowDirsOnly))------
[2023-03-08 17:12:21,947][log_print.py 81][ERROR]: selectfile is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 44, in selectfile
    self.filePath = QFileDialog.getExistingDirectory(self.ui, "选择存储路径")
TypeError: 'PySide6.QtWidgets.QFileDialog.getExistingDirectory' called with wrong argument types:
  PySide6.QtWidgets.QFileDialog.getExistingDirectory(Ui_Form, str)
Supported signatures:
  PySide6.QtWidgets.QFileDialog.getExistingDirectory(Optional[PySide6.QtWidgets.QWidget] = None, str = '', str = '', PySide6.QtWidgets.QFileDialog.Option = Instance(PySide6.QtWidgets.QFileDialog.Option.ShowDirsOnly))

[2023-03-08 17:13:44,685][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:13:44,821][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:13:50,304][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 17:14:02,258][log_print.py 80][ERROR]: ------selectfile执行失败：'MyWidget' object has no attribute 'filename'------
[2023-03-08 17:14:02,262][log_print.py 81][ERROR]: selectfile is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 46, in selectfile
    self.ui.lineEdit2_1.setText(self.filename)
AttributeError: 'MyWidget' object has no attribute 'filename'

[2023-03-08 17:15:46,784][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:15:46,944][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:15:56,069][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 17:16:00,964][log_print.py 80][ERROR]: ------selectfile执行失败：'MyWidget' object has no attribute 'albumpath'------
[2023-03-08 17:16:00,965][log_print.py 81][ERROR]: selectfile is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 46, in selectfile
    self.ui.lineEdit2_1.setText(self.albumpath)
AttributeError: 'MyWidget' object has no attribute 'albumpath'

[2023-03-08 17:23:53,264][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:23:53,422][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:25:10,709][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:25:10,857][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:26:08,296][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 17:26:08,431][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 17:26:15,139][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 17:26:19,062][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 17:26:25,071][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 17:26:26,953][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 17:26:33,218][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 17:26:45,751][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:17:52,024][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:17:52,272][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:18:20,573][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:18:20,753][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:18:39,399][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:18:39,592][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:19:20,297][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:19:20,461][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:19:33,737][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:19:38,447][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:19:43,962][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:19:43,965][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:20:51,941][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:20:52,132][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:21:06,872][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:21:09,781][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:21:11,202][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:21:12,696][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:21:14,398][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:21:17,194][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:21:19,009][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:21:19,011][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:21:21,666][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 18:21:31,668][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 18:21:46,471][log_print.py 75][INFO]: ------开始执行downlo-----
[2023-03-08 18:21:59,179][log_print.py 85][INFO]: ------downlo执行成功------
[2023-03-08 18:22:12,333][log_print.py 75][INFO]: ------开始执行downlo-----
[2023-03-08 18:22:24,008][log_print.py 85][INFO]: ------downlo执行成功------
[2023-03-08 18:28:43,859][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:28:44,115][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:28:48,994][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:28:53,041][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:28:55,123][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:28:55,125][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:28:57,592][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 18:28:57,594][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 18:34:17,905][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:34:18,152][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:34:23,812][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:34:28,555][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:34:30,772][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:34:30,776][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:34:34,126][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 18:34:34,129][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 18:37:26,084][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:37:26,381][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:37:32,485][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:37:35,908][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:37:38,549][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:37:38,552][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:37:41,509][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 18:37:41,512][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 18:38:31,298][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:38:31,506][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:39:10,066][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:39:10,266][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:39:16,267][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:39:18,842][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:39:20,731][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:39:20,734][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:39:24,837][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 18:39:24,839][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 18:42:23,942][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:42:24,144][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 18:42:29,795][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 18:42:33,204][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 18:42:36,075][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 18:42:36,079][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 18:42:38,654][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 18:42:38,657][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 18:42:50,658][log_print.py 75][INFO]: ------开始执行downlo-----
[2023-03-08 18:43:02,145][log_print.py 85][INFO]: ------downlo执行成功------
[2023-03-08 18:57:31,209][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 18:57:31,456][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 19:10:14,470][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 19:10:14,751][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 19:10:18,310][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 19:10:22,082][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 19:10:24,524][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 19:10:24,540][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 19:10:26,143][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 19:10:26,144][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:00:41,077][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:00:41,272][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:00:44,543][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:00:49,306][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:00:54,199][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:00:54,223][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:00:55,786][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:00:55,796][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:07:13,397][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:07:13,656][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:07:17,446][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:07:21,113][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:07:25,906][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:07:25,922][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:07:26,682][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:07:26,685][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:20:46,114][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:20:46,350][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:20:50,629][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:20:54,386][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:21:01,430][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:21:01,436][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:21:02,431][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:21:02,433][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:25:03,201][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:25:03,465][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:25:09,638][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:25:13,908][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:25:20,618][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:25:20,638][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:25:21,465][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:25:21,470][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:26:31,520][log_print.py 75][INFO]: ------开始执行downlo-----
[2023-03-08 20:26:43,468][log_print.py 85][INFO]: ------downlo执行成功------
[2023-03-08 20:28:33,839][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:28:34,069][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:28:37,354][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:28:40,465][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:28:46,932][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:28:46,953][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:28:47,979][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:28:47,984][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:30:36,692][log_print.py 75][INFO]: ------开始执行downlo-----
[2023-03-08 20:30:48,428][log_print.py 85][INFO]: ------downlo执行成功------
[2023-03-08 20:49:20,080][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:49:20,315][log_print.py 80][ERROR]: ------__init__执行失败：'MyWidget' object has no attribute 'downlo'------
[2023-03-08 20:49:20,316][log_print.py 81][ERROR]: __init__ is error,here are details:Traceback (most recent call last):
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/log_print.py", line 77, in log
    func(*args,**kwargs)
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 36, in __init__
    self.tab3()
  File "/Users/Github_Library/My_Case/QQSpace_Album_Download/UIdraft.py", line 63, in tab3
    self.ui.pushButton3_2.clicked.connect(self.downlo)
AttributeError: 'MyWidget' object has no attribute 'downlo'

[2023-03-08 20:50:27,287][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:50:27,476][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:50:31,299][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:50:35,014][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:50:39,764][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:50:39,779][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:50:41,137][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:50:41,140][log_print.py 75][INFO]: ------开始执行loginUI2-----
[2023-03-08 20:50:41,140][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:51:33,698][log_print.py 85][INFO]: ------loginUI2执行成功------
[2023-03-08 20:51:44,364][log_print.py 75][INFO]: ------开始执行get_pageUI-----
[2023-03-08 20:51:46,026][log_print.py 75][INFO]: ------开始执行get_pageUI2-----
[2023-03-08 20:51:46,026][log_print.py 85][INFO]: ------get_pageUI执行成功------
[2023-03-08 20:53:04,362][log_print.py 85][INFO]: ------get_pageUI2执行成功------
[2023-03-08 20:55:38,361][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:55:38,618][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:55:41,395][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:55:44,684][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:55:49,916][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:55:49,941][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:56:21,144][log_print.py 75][INFO]: ------开始执行__init__-----
[2023-03-08 20:56:21,400][log_print.py 85][INFO]: ------__init__执行成功------
[2023-03-08 20:56:23,871][log_print.py 75][INFO]: ------开始执行selectfile-----
[2023-03-08 20:56:29,616][log_print.py 85][INFO]: ------selectfile执行成功------
[2023-03-08 20:56:34,491][log_print.py 75][INFO]: ------开始执行checkdata-----
[2023-03-08 20:56:34,501][log_print.py 85][INFO]: ------checkdata执行成功------
[2023-03-08 20:56:36,443][log_print.py 75][INFO]: ------开始执行loginUI-----
[2023-03-08 20:56:36,447][log_print.py 75][INFO]: ------开始执行loginUI2-----
[2023-03-08 20:56:36,447][log_print.py 85][INFO]: ------loginUI执行成功------
[2023-03-08 20:57:42,870][log_print.py 85][INFO]: ------loginUI2执行成功------
[2023-03-08 20:57:45,335][log_print.py 75][INFO]: ------开始执行get_pageUI-----
[2023-03-08 20:57:46,860][log_print.py 75][INFO]: ------开始执行get_pageUI2-----
[2023-03-08 20:57:46,860][log_print.py 85][INFO]: ------get_pageUI执行成功------
[2023-03-08 20:57:53,538][log_print.py 85][INFO]: ------get_pageUI2执行成功------
